-- Script creacion BD RecetasChef
CREATE DATABASE IF NOT EXISTS recetasdb CHARACTER SET utf8mb4;
USE recetasdb;
CREATE TABLE IF NOT EXISTS usuarios (id BIGINT AUTO_INCREMENT PRIMARY KEY, username VARCHAR(50) NOT NULL UNIQUE, password VARCHAR(255) NOT NULL, roles VARCHAR(100) NOT NULL);
